/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Header: typeof import('./components/Header/index.vue')['default']
    LangSwitch: typeof import('./components/Header/LangSwitch/index.vue')['default']
    SearchInput: typeof import('./components/SearchInput/index.vue')['default']
    ThemeSwitch: typeof import('./components/Header/ThemeSwitch/index.vue')['default']
    Title: typeof import('./components/Header/Title/index.vue')['default']
    WebsiteList: typeof import('./components/WebsiteList/index.vue')['default']
  }
}
