/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Header: typeof import('./components/Header/index.vue')['default']
    LangSwitch: typeof import('./components/Header/LangSwitch/index.vue')['default']
    PlaybackControls: typeof import('./components/WhiteNoise/PlaybackControls.vue')['default']
    PresetHeader: typeof import('./components/WhiteNoise/PresetHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/SearchInput/index.vue')['default']
    SoundCard: typeof import('./components/WhiteNoise/SoundCard.vue')['default']
    ThemeSwitch: typeof import('./components/Header/ThemeSwitch/index.vue')['default']
    Title: typeof import('./components/Header/Title/index.vue')['default']
    VisualizerCanvas: typeof import('./components/WhiteNoise/VisualizerCanvas.vue')['default']
    WebsiteList: typeof import('./components/WebsiteList/index.vue')['default']
  }
}
